schema_version: "1.0"
mcp_name: "Sanctions Law MCP"
jurisdiction: "INTL"
deployment_strategy: "Strategy A (Vercel)"

sources:
  - name: "UN Security Council sanctions resolutions"
    authority: "United Nations Security Council"
    official_portal: "https://www.un.org/securitycouncil/sanctions/information"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "on_change"
    records_estimate: "~200"
    priority: "critical"
    coverage_note: "Primary legal basis for UN sanctions regimes"
    license_or_terms:
      type: "official_publication"
      url: "https://www.un.org/securitycouncil/sanctions/information"
      summary: "Use official publications and verify redistribution terms before bulk replication."
    languages:
      - "en"
  - name: "UN sanctions committee guidance"
    authority: "United Nations Security Council"
    official_portal: "https://main.un.org/securitycouncil/en/sanctions/information"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "on_change"
    records_estimate: "~50"
    priority: "high"
    coverage_note: "Exemption and designation criteria guidance"
    license_or_terms:
      type: "official_publication"
      url: "https://main.un.org/securitycouncil/en/sanctions/information"
      summary: "Use official publications and verify redistribution terms before bulk replication."
    languages:
      - "en"
  - name: "EU restrictive measures legal texts"
    authority: "Council of the European Union"
    official_portal: "https://www.consilium.europa.eu/en/policies/sanctions/"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "on_change"
    records_estimate: "~100"
    priority: "critical"
    coverage_note: "CFSP decisions and regulations legal basis"
    license_or_terms:
      type: "official_publication"
      url: "https://www.consilium.europa.eu/en/policies/sanctions/"
      summary: "Use official publications and verify redistribution terms before bulk replication."
    languages:
      - "en"
  - name: "US OFAC executive orders and guidance"
    authority: "US Department of the Treasury"
    official_portal: "https://ofac.treasury.gov"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "on_change"
    records_estimate: "~130"
    priority: "critical"
    coverage_note: "EOs, FAQs, and legal interpretive guidance"
    license_or_terms:
      type: "official_publication"
      url: "https://ofac.treasury.gov"
      summary: "Use official publications and verify redistribution terms before bulk replication."
    languages:
      - "en"
  - name: "US BIS Export Administration Regulations"
    authority: "US Bureau of Industry and Security"
    official_portal: "https://www.bis.gov"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "on_change"
    records_estimate: "Key sections"
    priority: "high"
    coverage_note: "Export controls with cyber and dual-use relevance"
    license_or_terms:
      type: "official_publication"
      url: "https://www.bis.gov"
      summary: "Use official publications and verify redistribution terms before bulk replication."
    languages:
      - "en"
  - name: "UK OFSI sanctions regulations"
    authority: "UK Office of Financial Sanctions Implementation"
    official_portal: "https://www.gov.uk/government/organisations/office-of-financial-sanctions-implementation"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "on_change"
    records_estimate: "~30"
    priority: "high"
    coverage_note: "Post-Brexit UK autonomous sanctions legal basis"
    license_or_terms:
      type: "official_publication"
      url: "https://www.gov.uk/government/organisations/office-of-financial-sanctions-implementation"
      summary: "Use official publications and verify redistribution terms before bulk replication."
    languages:
      - "en"
  - name: "CJEU sanctions case law"
    authority: "Court of Justice of the European Union"
    official_portal: "https://curia.europa.eu"
    retrieval_method: "HTML_SCRAPE"
    update_frequency: "monthly"
    records_estimate: "~100"
    priority: "high"
    coverage_note: "Judicial review and delisting jurisprudence"
    license_or_terms:
      type: "official_publication"
      url: "https://curia.europa.eu"
      summary: "Use official publications and verify redistribution terms before bulk replication."
    languages:
      - "en"

data_freshness:
  automated_checks: true
  check_frequency: "daily"
  last_verified: "2026-02-22"
