import type { SanctionsSeed } from './types.js';

export const DEFAULT_SANCTIONS_SEED: SanctionsSeed = {
  schema_version: '1.0',
  generated_on: '2026-02-22',
  sources: [
    {
      id: 'UN_SC_RESOLUTIONS',
      name: 'UN Security Council sanctions resolutions',
      authority: 'United Nations Security Council',
      official_portal: 'https://www.un.org/securitycouncil/sanctions/information',
      retrieval_method: 'HTML_SCRAPE',
      update_frequency: 'on_change',
      records_estimate: '~200',
      priority: 'critical',
      coverage_note: 'Primary legal basis for UN sanctions regimes and committee mandates.',
      last_verified: '2026-02-20',
      metadata: {
        languages: ['en'],
      },
    },
    {
      id: 'UN_COMMITTEE_GUIDANCE',
      name: 'UN sanctions committee guidance',
      authority: 'United Nations Security Council',
      official_portal: 'https://main.un.org/securitycouncil/en/sanctions/information',
      retrieval_method: 'HTML_SCRAPE',
      update_frequency: 'on_change',
      records_estimate: '~50',
      priority: 'high',
      coverage_note: 'Implementation notes, exemptions, and focal-point delisting mechanics.',
      last_verified: '2026-02-20',
      metadata: {
        languages: ['en'],
      },
    },
    {
      id: 'EU_RESTRICTIVE_MEASURES',
      name: 'EU restrictive measures legal texts',
      authority: 'Council of the European Union',
      official_portal: 'https://www.consilium.europa.eu/en/policies/sanctions/',
      retrieval_method: 'HTML_SCRAPE',
      update_frequency: 'on_change',
      records_estimate: '~100',
      priority: 'critical',
      coverage_note: 'CFSP decisions and implementing regulations for EU sanctions regimes.',
      last_verified: '2026-02-21',
      metadata: {
        languages: ['en'],
      },
    },
    {
      id: 'US_OFAC_EXECUTIVE_ORDERS',
      name: 'US OFAC executive orders and guidance',
      authority: 'US Department of the Treasury',
      official_portal: 'https://ofac.treasury.gov',
      retrieval_method: 'HTML_SCRAPE',
      update_frequency: 'on_change',
      records_estimate: '~130',
      priority: 'critical',
      coverage_note: 'Executive orders and OFAC guidance documents that establish sanctions authority.',
      last_verified: '2026-02-21',
      metadata: {
        languages: ['en'],
      },
    },
    {
      id: 'US_BIS_EAR',
      name: 'US BIS Export Administration Regulations',
      authority: 'US Bureau of Industry and Security',
      official_portal: 'https://www.bis.gov',
      retrieval_method: 'HTML_SCRAPE',
      update_frequency: 'on_change',
      records_estimate: 'Key sections',
      priority: 'high',
      coverage_note: 'Export control authorities tied to sanctions and dual-use compliance.',
      last_verified: '2026-02-19',
      metadata: {
        languages: ['en'],
      },
    },
    {
      id: 'UK_OFSI_REGULATIONS',
      name: 'UK OFSI sanctions regulations',
      authority: 'UK Office of Financial Sanctions Implementation',
      official_portal: 'https://www.gov.uk/government/organisations/office-of-financial-sanctions-implementation',
      retrieval_method: 'HTML_SCRAPE',
      update_frequency: 'on_change',
      records_estimate: '~30',
      priority: 'high',
      coverage_note: 'UK sanctions framework post-Brexit including autonomous designation powers.',
      last_verified: '2026-02-21',
      metadata: {
        languages: ['en'],
      },
    },
    {
      id: 'CJEU_SANCTIONS_CASE_LAW',
      name: 'CJEU sanctions case law',
      authority: 'Court of Justice of the European Union',
      official_portal: 'https://curia.europa.eu',
      retrieval_method: 'HTML_SCRAPE',
      update_frequency: 'monthly',
      records_estimate: '~100',
      priority: 'high',
      coverage_note: 'Judicial review jurisprudence for listing, evidence, and procedural rights.',
      last_verified: '2026-02-18',
      metadata: {
        languages: ['en'],
      },
    },
  ],
  sanctions_regimes: [
    {
      id: 'UN_DPRK_1718',
      name: 'UN DPRK sanctions regime (1718 Committee)',
      jurisdiction: 'UN',
      authority: 'UN Security Council',
      summary:
        'Security Council measures on DPRK proliferation activities, including asset freezes and sectoral restrictions.',
      legal_basis: ['UNSCR 1718 (2006)', 'UNSCR 2397 (2017)'],
      cyber_related: false,
      delisting_procedure_id: 'DP_UN_FOCAL_POINT',
      official_url: 'https://www.un.org/securitycouncil/sanctions/1718',
    },
    {
      id: 'EU_RUSSIA_2014',
      name: 'EU restrictive measures concerning actions undermining Ukraine',
      jurisdiction: 'EU',
      authority: 'Council of the European Union',
      summary:
        'Sectoral and listing-based EU sanctions framework with finance, energy, and export restrictions.',
      legal_basis: ['Council Decision 2014/512/CFSP', 'Council Regulation (EU) No 833/2014'],
      cyber_related: false,
      delisting_procedure_id: 'DP_EU_REEXAMINATION',
      official_url: 'https://www.consilium.europa.eu/en/policies/sanctions/restrictive-measures-against-russia-over-ukraine/',
    },
    {
      id: 'US_CYBER_13694',
      name: 'US malicious cyber-enabled activities sanctions program',
      jurisdiction: 'US',
      authority: 'US Department of the Treasury (OFAC)',
      summary:
        'Program authority for designations tied to significant malicious cyber-enabled activity and election interference.',
      legal_basis: ['Executive Order 13694', 'Executive Order 13757', 'Executive Order 13848'],
      cyber_related: true,
      delisting_procedure_id: 'DP_US_OFAC_RECONSIDERATION',
      official_url: 'https://ofac.treasury.gov/sanctions-programs-and-country-information/cyber-related-sanctions',
    },
    {
      id: 'EU_CYBER_2019_796',
      name: 'EU cyber-attacks restrictive measures framework',
      jurisdiction: 'EU',
      authority: 'Council of the European Union',
      summary:
        'Targeted restrictive measures against persons and entities responsible for cyber-attacks threatening the Union.',
      legal_basis: ['Council Regulation (EU) 2019/796', 'Council Decision (CFSP) 2019/797'],
      cyber_related: true,
      delisting_procedure_id: 'DP_EU_REEXAMINATION',
      official_url: 'https://www.consilium.europa.eu/en/policies/cyber-attacks/',
    },
    {
      id: 'UK_GLOBAL_ANTI_CORRUPTION',
      name: 'UK Global Anti-Corruption sanctions regime',
      jurisdiction: 'UK',
      authority: 'HM Treasury / OFSI',
      summary:
        'Autonomous UK sanctions framework for serious corruption with designation and asset-freeze powers.',
      legal_basis: ['Sanctions and Anti-Money Laundering Act 2018', 'Global Anti-Corruption Sanctions Regulations 2021'],
      cyber_related: false,
      delisting_procedure_id: 'DP_UK_OFSI_REVIEW',
      official_url: 'https://www.gov.uk/government/publications/uk-sanctions-guidance',
    },
    {
      id: 'UK_RUSSIA_REGIME',
      name: 'UK Russia sanctions regime',
      jurisdiction: 'UK',
      authority: 'HM Treasury / OFSI',
      summary:
        'UK sanctions framework concerning Russia, including trade, financial, and designation measures.',
      legal_basis: ['Russia (Sanctions) (EU Exit) Regulations 2019'],
      cyber_related: false,
      delisting_procedure_id: 'DP_UK_OFSI_REVIEW',
      official_url: 'https://www.legislation.gov.uk/uksi/2019/855/contents',
    },
  ],
  provisions: [
    {
      source_id: 'UN_SC_RESOLUTIONS',
      item_id: 'UNSCR1718_OP8',
      title: 'UNSCR 1718 operative paragraph 8',
      text:
        'Operative paragraph 8 establishes asset freeze, travel ban, and arms-related restrictions tied to DPRK proliferation risks.',
      parent: 'UNSCR 1718 (2006)',
      kind: 'resolution_paragraph',
      regime_id: 'UN_DPRK_1718',
      issued_on: '2006-10-14',
      url: 'https://undocs.org/S/RES/1718(2006)',
      topics: ['asset_freeze', 'travel_ban', 'arms_embargo'],
      metadata: {
        citation: 'S/RES/1718 (2006) OP8',
      },
    },
    {
      source_id: 'UN_SC_RESOLUTIONS',
      item_id: 'UNSCR2397_OP6',
      title: 'UNSCR 2397 operative paragraph 6',
      text:
        'Operative paragraph 6 tightens maritime and petroleum controls and expands enforcement expectations for member states.',
      parent: 'UNSCR 2397 (2017)',
      kind: 'resolution_paragraph',
      regime_id: 'UN_DPRK_1718',
      issued_on: '2017-12-22',
      url: 'https://undocs.org/S/RES/2397(2017)',
      topics: ['maritime_controls', 'sectoral_restrictions', 'enforcement'],
      metadata: {
        citation: 'S/RES/2397 (2017) OP6',
      },
    },
    {
      source_id: 'UN_COMMITTEE_GUIDANCE',
      item_id: 'UN_FOCAL_POINT_DELISTING',
      title: 'UN focal point delisting process',
      text:
        'Guidance outlines petition routes for listed persons and entities, required supporting evidence, and committee review stages.',
      parent: 'Delisting guidance',
      kind: 'committee_guidance',
      regime_id: 'UN_DPRK_1718',
      issued_on: '2018-06-01',
      url: 'https://www.un.org/securitycouncil/sanctions/delisting/focalpoint',
      topics: ['delisting', 'due_process', 'petition'],
      metadata: {
        process_owner: 'UN Focal Point for Delisting',
      },
    },
    {
      source_id: 'EU_RESTRICTIVE_MEASURES',
      item_id: 'EU833_ART2',
      title: 'Regulation (EU) 833/2014 Article 2',
      text:
        'Article 2 contains prohibitions and authorization rules for export and transfer of certain dual-use goods to Russia.',
      parent: 'Regulation (EU) 833/2014',
      kind: 'regulation_article',
      regime_id: 'EU_RUSSIA_2014',
      issued_on: '2014-07-31',
      url: 'https://eur-lex.europa.eu/eli/reg/2014/833/oj',
      topics: ['export_controls', 'dual_use', 'authorization'],
      metadata: {
        celex: '32014R0833',
      },
    },
    {
      source_id: 'EU_RESTRICTIVE_MEASURES',
      item_id: 'EU512_ART4',
      title: 'Decision 2014/512/CFSP Article 4',
      text:
        'Article 4 establishes financing and assistance restrictions for specified military and dual-use transactions.',
      parent: 'Decision 2014/512/CFSP',
      kind: 'decision_article',
      regime_id: 'EU_RUSSIA_2014',
      issued_on: '2014-07-31',
      url: 'https://eur-lex.europa.eu/eli/dec/2014/512/oj',
      topics: ['financing_restrictions', 'military_goods', 'dual_use'],
      metadata: {
        celex: '32014D0512',
      },
    },
    {
      source_id: 'EU_RESTRICTIVE_MEASURES',
      item_id: 'EU2019_796_ART5',
      title: 'Regulation (EU) 2019/796 Article 5',
      text:
        'Article 5 sets out derogation mechanics and competent authority responsibilities under the EU cyber sanctions framework.',
      parent: 'Regulation (EU) 2019/796',
      kind: 'regulation_article',
      regime_id: 'EU_CYBER_2019_796',
      issued_on: '2019-05-17',
      url: 'https://eur-lex.europa.eu/eli/reg/2019/796/oj',
      topics: ['cyber', 'asset_freeze', 'derogations'],
      metadata: {
        celex: '32019R0796',
      },
    },
    {
      source_id: 'US_OFAC_EXECUTIVE_ORDERS',
      item_id: 'EO13694_SEC1',
      title: 'Executive Order 13694 Section 1',
      text:
        'Section 1 authorizes blocking sanctions against persons responsible for significant malicious cyber-enabled activities.',
      parent: 'Executive Order 13694',
      kind: 'executive_order_section',
      regime_id: 'US_CYBER_13694',
      issued_on: '2015-04-01',
      url: 'https://www.federalregister.gov/documents/2015/04/02/2015-07788/blocking-the-property-of-certain-persons-engaging-in-significant-malicious-cyber-enabled-activities',
      topics: ['cyber', 'blocking_sanctions', 'designation_authority'],
      metadata: {
        federal_register: '80 FR 18077',
      },
    },
    {
      source_id: 'US_OFAC_EXECUTIVE_ORDERS',
      item_id: 'OFAC_FAQ_595',
      title: 'OFAC FAQ 595',
      text:
        'FAQ guidance explains compliance expectations for dealing with cyber-related sanctioned persons and blocked property.',
      parent: 'OFAC FAQs',
      kind: 'guidance',
      regime_id: 'US_CYBER_13694',
      issued_on: '2023-03-10',
      url: 'https://ofac.treasury.gov/faqs/topic/1571',
      topics: ['cyber', 'compliance', 'blocked_property'],
      metadata: {
        faq: '595',
      },
    },
    {
      source_id: 'US_BIS_EAR',
      item_id: 'EAR744_21',
      title: 'EAR Part 744.21 military end-use and end-user controls',
      text:
        'Part 744.21 sets licensing requirements for military end-use and military end-user exports to listed destinations.',
      parent: '15 CFR Part 744',
      kind: 'regulation_section',
      regime_id: null,
      issued_on: '2020-12-23',
      url: 'https://www.ecfr.gov/current/title-15/subtitle-B/chapter-VII/subchapter-C/part-744',
      topics: ['export_controls', 'licensing', 'military_end_use'],
      metadata: {
        cfr: '15 CFR 744.21',
      },
    },
    {
      source_id: 'US_BIS_EAR',
      item_id: 'EAR746_8',
      title: 'EAR Part 746.8 Russia and Belarus sanctions',
      text:
        'Part 746.8 describes license requirements and policy standards for Russia and Belarus related exports and reexports.',
      parent: '15 CFR Part 746',
      kind: 'regulation_section',
      regime_id: null,
      issued_on: '2022-03-03',
      url: 'https://www.ecfr.gov/current/title-15/subtitle-B/chapter-VII/subchapter-C/part-746',
      topics: ['export_controls', 'russia', 'belarus', 'license_policy'],
      metadata: {
        cfr: '15 CFR 746.8',
      },
    },
    {
      source_id: 'UK_OFSI_REGULATIONS',
      item_id: 'SAMLA2018_SEC1',
      title: 'Sanctions and Anti-Money Laundering Act 2018 Section 1',
      text:
        'Section 1 sets the principal statutory purposes for UK sanctions regulations and ministerial powers.',
      parent: 'Sanctions and Anti-Money Laundering Act 2018',
      kind: 'act_section',
      regime_id: 'UK_GLOBAL_ANTI_CORRUPTION',
      issued_on: '2018-05-23',
      url: 'https://www.legislation.gov.uk/ukpga/2018/13/contents',
      topics: ['legal_basis', 'designation_powers', 'uk_framework'],
      metadata: {
        legislation_gov_uk: 'ukpga/2018/13',
      },
    },
    {
      source_id: 'UK_OFSI_REGULATIONS',
      item_id: 'UKRUSSIA2019_REG11',
      title: 'Russia (Sanctions) (EU Exit) Regulations 2019 Regulation 11',
      text:
        'Regulation 11 describes criteria for designation linked to destabilizing conduct and connected support.',
      parent: 'Russia (Sanctions) (EU Exit) Regulations 2019',
      kind: 'regulation_section',
      regime_id: 'UK_RUSSIA_REGIME',
      issued_on: '2019-04-08',
      url: 'https://www.legislation.gov.uk/uksi/2019/855/contents',
      topics: ['designation_criteria', 'asset_freeze', 'uk_russia'],
      metadata: {
        legislation_gov_uk: 'uksi/2019/855',
      },
    },
    {
      source_id: 'CJEU_SANCTIONS_CASE_LAW',
      item_id: 'C72_15_ROSNEFT_HOLDING',
      title: 'C-72/15 Rosneft holding summary',
      text:
        'The Court confirmed jurisdiction to review restrictive measures and upheld core EU Russia sanctions provisions under judicial scrutiny.',
      parent: 'C-72/15 Rosneft',
      kind: 'case_law_holding',
      regime_id: 'EU_RUSSIA_2014',
      issued_on: '2017-03-28',
      url: 'https://curia.europa.eu',
      topics: ['judicial_review', 'russia', 'cfsp'],
      metadata: {
        case_reference: 'C-72/15',
      },
    },
  ],
  executive_orders: [
    {
      id: 'EO_13694',
      source_id: 'US_OFAC_EXECUTIVE_ORDERS',
      regime_id: 'US_CYBER_13694',
      order_number: '13694',
      title: 'Blocking the Property of Certain Persons Engaging in Significant Malicious Cyber-Enabled Activities',
      issued_on: '2015-04-01',
      status: 'active',
      summary:
        'Establishes sanctions authority for significant malicious cyber-enabled activities threatening US national security and economy.',
      cyber_related: true,
      legal_basis: ['Executive Order 13694'],
      official_url:
        'https://www.federalregister.gov/documents/2015/04/02/2015-07788/blocking-the-property-of-certain-persons-engaging-in-significant-malicious-cyber-enabled-activities',
    },
    {
      id: 'EO_13757',
      source_id: 'US_OFAC_EXECUTIVE_ORDERS',
      regime_id: 'US_CYBER_13694',
      order_number: '13757',
      title: 'Taking Additional Steps to Address the National Emergency With Respect to Significant Malicious Cyber-Enabled Activities',
      issued_on: '2016-12-28',
      status: 'active',
      summary:
        'Amends and strengthens cyber-related blocking criteria under EO 13694.',
      cyber_related: true,
      legal_basis: ['Executive Order 13757', 'Executive Order 13694'],
      official_url:
        'https://www.federalregister.gov/documents/2017/01/03/2016-31922/taking-additional-steps-to-address-the-national-emergency-with-respect-to-significant-malicious',
    },
    {
      id: 'EO_13848',
      source_id: 'US_OFAC_EXECUTIVE_ORDERS',
      regime_id: 'US_CYBER_13694',
      order_number: '13848',
      title: 'Imposing Certain Sanctions in the Event of Foreign Interference in a United States Election',
      issued_on: '2018-09-12',
      status: 'active',
      summary:
        'Authorizes sanctions responses for specified forms of foreign election interference.',
      cyber_related: true,
      legal_basis: ['Executive Order 13848'],
      official_url:
        'https://www.federalregister.gov/documents/2018/09/14/2018-20203/imposing-certain-sanctions-in-the-event-of-foreign-interference-in-a-united-states-election',
    },
    {
      id: 'EO_14024',
      source_id: 'US_OFAC_EXECUTIVE_ORDERS',
      regime_id: null,
      order_number: '14024',
      title: 'Blocking Property With Respect to Specified Harmful Foreign Activities of the Government of the Russian Federation',
      issued_on: '2021-04-15',
      status: 'active',
      summary:
        'Creates sanctions authorities for specified harmful Russian government activities, including cyber-enabled operations.',
      cyber_related: true,
      legal_basis: ['Executive Order 14024'],
      official_url:
        'https://www.federalregister.gov/documents/2021/04/19/2021-08076/blocking-property-with-respect-to-specified-harmful-foreign-activities-of-the-government-of-the',
    },
  ],
  delisting_procedures: [
    {
      id: 'DP_UN_FOCAL_POINT',
      regime_id: 'UN_DPRK_1718',
      authority: 'UN Security Council Focal Point for Delisting',
      procedure_summary:
        'Petitioners submit a delisting request with supporting information through the focal point route for committee consideration.',
      evidentiary_standard: 'Reasoned submission showing listing criteria are no longer met or were misapplied.',
      review_body: '1718 Sanctions Committee',
      review_timeline: 'No fixed statutory deadline; committee practice varies by case complexity.',
      application_url: 'https://www.un.org/securitycouncil/sanctions/delisting/focalpoint',
      legal_basis: ['UNSCR 1730 (2006)', 'UN focal point guidelines'],
    },
    {
      id: 'DP_EU_REEXAMINATION',
      regime_id: 'EU_RUSSIA_2014',
      authority: 'Council of the European Union',
      procedure_summary:
        'Listed parties may request re-examination by the Council and challenge listings before EU courts.',
      evidentiary_standard: 'Submissions should address factual findings, identity, and proportionality of listing grounds.',
      review_body: 'Council Working Parties and CJEU judicial review',
      review_timeline: 'Administrative re-examination and court timelines vary; interim relief may be sought in litigation.',
      application_url: 'https://www.consilium.europa.eu/en/policies/sanctions/',
      legal_basis: ['Article 275 TFEU', 'EU sanctions best practices guidance'],
    },
    {
      id: 'DP_US_OFAC_RECONSIDERATION',
      regime_id: 'US_CYBER_13694',
      authority: 'US Department of the Treasury (OFAC)',
      procedure_summary:
        'Designated parties can submit a reconsideration request with legal and factual arguments to OFAC.',
      evidentiary_standard: 'Comprehensive documentation showing changed circumstances or identity errors.',
      review_body: 'OFAC Office of Global Targeting and Licensing divisions',
      review_timeline: 'No fixed adjudication timeline; outcomes depend on case complexity and submissions.',
      application_url: 'https://ofac.treasury.gov/sanctions-programs-and-country-information',
      legal_basis: ['31 CFR 501.807'],
    },
    {
      id: 'DP_UK_OFSI_REVIEW',
      regime_id: 'UK_GLOBAL_ANTI_CORRUPTION',
      authority: 'HM Treasury / OFSI',
      procedure_summary:
        'Designated persons may request ministerial review and may challenge decisions before UK courts.',
      evidentiary_standard: 'Representations should address designation criteria and supporting evidence.',
      review_body: 'Foreign, Commonwealth and Development Office / UK courts',
      review_timeline: 'Ministerial review and judicial review timelines depend on procedural posture.',
      application_url: 'https://www.gov.uk/government/publications/sanctions-guidance-for-the-financial-services-sector',
      legal_basis: ['Sanctions and Anti-Money Laundering Act 2018'],
    },
  ],
  export_controls: [
    {
      id: 'EAR_744_21',
      source_id: 'US_BIS_EAR',
      jurisdiction: 'US',
      instrument: 'Export Administration Regulations',
      section: '15 CFR 744.21',
      title: 'Military end-use and military end-user controls',
      summary:
        'Introduces controls requiring licenses for identified military end-use and military end-user activities.',
      focus: 'military end-use',
      official_url: 'https://www.ecfr.gov/current/title-15/subtitle-B/chapter-VII/subchapter-C/part-744',
    },
    {
      id: 'EAR_746_8',
      source_id: 'US_BIS_EAR',
      jurisdiction: 'US',
      instrument: 'Export Administration Regulations',
      section: '15 CFR 746.8',
      title: 'Russia and Belarus industry sector sanctions',
      summary:
        'Defines broad license requirements and policy standards for controlled exports linked to Russia and Belarus.',
      focus: 'country sanctions controls',
      official_url: 'https://www.ecfr.gov/current/title-15/subtitle-B/chapter-VII/subchapter-C/part-746',
    },
    {
      id: 'EU_833_ART2',
      source_id: 'EU_RESTRICTIVE_MEASURES',
      jurisdiction: 'EU',
      instrument: 'Council Regulation (EU) No 833/2014',
      section: 'Article 2',
      title: 'Dual-use goods and technology restrictions',
      summary:
        'Sets export prohibitions and authorization conditions for designated dual-use items.',
      focus: 'dual-use controls',
      official_url: 'https://eur-lex.europa.eu/eli/reg/2014/833/oj',
    },
    {
      id: 'UK_RUSSIA_PART5',
      source_id: 'UK_OFSI_REGULATIONS',
      jurisdiction: 'UK',
      instrument: 'Russia (Sanctions) (EU Exit) Regulations 2019',
      section: 'Part 5',
      title: 'Trade and export restrictions',
      summary:
        'Contains trade and export restrictions with licensing pathways administered by UK competent authorities.',
      focus: 'trade sanctions',
      official_url: 'https://www.legislation.gov.uk/uksi/2019/855/contents',
    },
  ],
  sanctions_case_law: [
    {
      id: 'C72_15_ROSNEFT',
      source_id: 'CJEU_SANCTIONS_CASE_LAW',
      court: 'Court of Justice of the European Union',
      case_reference: 'C-72/15',
      title: 'Rosneft preliminary ruling',
      decision_date: '2017-03-28',
      regime_id: 'EU_RUSSIA_2014',
      delisting_related: false,
      outcome: 'upheld core restrictive measures; clarified scope of judicial review',
      summary:
        'The judgment addressed jurisdiction and review standards for CFSP-linked restrictive measures in national proceedings.',
      keywords: ['judicial_review', 'cfsp', 'russia'],
      official_url: 'https://curia.europa.eu',
    },
    {
      id: 'T248_13_BANK_MELLAT',
      source_id: 'CJEU_SANCTIONS_CASE_LAW',
      court: 'General Court of the European Union',
      case_reference: 'T-248/13',
      title: 'Bank Mellat v Council',
      decision_date: '2016-06-02',
      regime_id: null,
      delisting_related: true,
      outcome: 'annulment based on deficiencies in evidentiary reasoning',
      summary:
        'The court scrutinized the evidentiary basis and statement of reasons supporting listing decisions.',
      keywords: ['delisting', 'evidence', 'statement_of_reasons'],
      official_url: 'https://curia.europa.eu',
    },
    {
      id: 'T715_14_ROSNEFT',
      source_id: 'CJEU_SANCTIONS_CASE_LAW',
      court: 'General Court of the European Union',
      case_reference: 'T-715/14',
      title: 'Rosneft and related applicants v Council',
      decision_date: '2018-09-13',
      regime_id: 'EU_RUSSIA_2014',
      delisting_related: false,
      outcome: 'claims largely dismissed; proportionality and legal basis arguments assessed',
      summary:
        'The court evaluated substantive and procedural challenges to EU sectoral Russia sanctions.',
      keywords: ['sectoral_sanctions', 'proportionality', 'russia'],
      official_url: 'https://curia.europa.eu',
    },
    {
      id: 'T262_15_KISELEV',
      source_id: 'CJEU_SANCTIONS_CASE_LAW',
      court: 'General Court of the European Union',
      case_reference: 'T-262/15',
      title: 'Kiselev v Council',
      decision_date: '2018-06-13',
      regime_id: 'EU_RUSSIA_2014',
      delisting_related: true,
      outcome: 'listing maintained after review of factual and procedural arguments',
      summary:
        'The court considered whether listing reasons and supporting evidence remained sufficient at renewal.',
      keywords: ['delisting', 'renewal', 'reasons'],
      official_url: 'https://curia.europa.eu',
    },
  ],
  source_freshness: [
    {
      source_id: 'UN_SC_RESOLUTIONS',
      last_checked: '2026-02-20',
      last_updated: '2025-12-15',
      check_frequency: 'daily',
      status: 'warning',
      notes: 'Daily polling active; no newer indexed resolution package detected.',
    },
    {
      source_id: 'UN_COMMITTEE_GUIDANCE',
      last_checked: '2026-02-20',
      last_updated: '2025-08-10',
      check_frequency: 'weekly',
      status: 'stale',
      notes: 'Guidance pages changed structure; re-ingestion parser update required.',
    },
    {
      source_id: 'EU_RESTRICTIVE_MEASURES',
      last_checked: '2026-02-21',
      last_updated: '2026-01-30',
      check_frequency: 'daily',
      status: 'fresh',
      notes: 'Latest amendment package ingested successfully.',
    },
    {
      source_id: 'US_OFAC_EXECUTIVE_ORDERS',
      last_checked: '2026-02-21',
      last_updated: '2026-02-15',
      check_frequency: 'daily',
      status: 'fresh',
      notes: 'Program pages and EO references aligned with current registry snapshot.',
    },
    {
      source_id: 'US_BIS_EAR',
      last_checked: '2026-02-19',
      last_updated: '2025-11-01',
      check_frequency: 'weekly',
      status: 'warning',
      notes: 'EAR sections monitored; pending validation against latest federal register notices.',
    },
    {
      source_id: 'UK_OFSI_REGULATIONS',
      last_checked: '2026-02-21',
      last_updated: '2026-02-05',
      check_frequency: 'daily',
      status: 'fresh',
      notes: 'Legislation and OFSI guidance pages ingested without parser drift.',
    },
    {
      source_id: 'CJEU_SANCTIONS_CASE_LAW',
      last_checked: '2026-02-18',
      last_updated: '2025-12-22',
      check_frequency: 'monthly',
      status: 'fresh',
      notes: 'Monthly polling cadence remains within target freshness window.',
    },
  ],
};
