/**
 * metadata.ts — Centralized metadata generation for all tool responses.
 *
 * Provides professional-use warnings, data freshness tracking, and source authority disclosure.
 */

import type { Database } from '@ansvar/mcp-sqlite';

export interface ResponseMetadata {
  /** Data freshness information */
  data_freshness: DataFreshness;

  /** Professional use disclaimer */
  disclaimer: string;

  /** Source authority disclosure */
  source_authority: SourceAuthority;

  /** Known coverage gaps */
  coverage_gaps: string[];

  /** EU AI Act transparency notice */
  ai_disclosure: string;
}

export interface DataFreshness {
  /** Last database update timestamp */
  sanctions_list_last_updated: string | null;

  /** Last sanctions data sync timestamp */
  sanctions_last_sync: string | null;

  /** Warning if data appears stale (>7 days — sanctions change frequently) */
  staleness_warning: string | null;
}

export interface SourceAuthority {
  /** Primary data source description */
  primary_source: string;

  /** Authority level assessment */
  authority_level: 'official' | 'community-maintained';

  /** Verification requirement */
  verification_required: string;
}

/**
 * Generate standard metadata for tool responses.
 *
 * This provides consistent professional-use warnings, data freshness tracking,
 * and source authority disclosure across all tools.
 *
 * @param db - Optional database handle. If not provided, data freshness checks are skipped.
 */
export function generateResponseMetadata(db?: Database): ResponseMetadata {
  const dataFreshness = db ? getDataFreshness(db) : getEmptyDataFreshness();
  const sourceAuthority = getSourceAuthority();

  return {
    data_freshness: dataFreshness,
    disclaimer: 'NOT LEGAL OR COMPLIANCE ADVICE. This tool is for research purposes only and does not constitute professional legal, sanctions, or compliance advice. Sanctions lists change frequently — sometimes daily. ALWAYS verify against current official sanctions lists before relying on output in screening, compliance, or enforcement matters. Users are solely responsible for verifying accuracy and currency of all information.',
    source_authority: sourceAuthority,
    coverage_gaps: [
      'Real-time sanctions updates (lists change daily)',
      'OFAC guidance and FAQs',
      'National sanctions implementation variations',
      'Sectoral sanctions program details'
    ],
    ai_disclosure: 'AI-assisted sanctions research tool. Results generated by algorithmic search and may contain errors or omissions. Human review required before professional use. Sanctions data is time-sensitive — always verify against live official sources.'
  };
}

/**
 * Return empty data freshness when database is not available.
 */
function getEmptyDataFreshness(): DataFreshness {
  return {
    sanctions_list_last_updated: null,
    sanctions_last_sync: null,
    staleness_warning: 'Data freshness information unavailable (tool does not query database). CRITICAL: Sanctions data changes frequently — always verify against live official sources.'
  };
}

/**
 * Check data freshness and generate staleness warnings.
 */
function getDataFreshness(db: Database): DataFreshness {
  // Check sanctions list last_updated
  let sanctionsListLastUpdated: string | null = null;
  try {
    const listRow = db.prepare(`
      SELECT MAX(last_updated) as max_date
      FROM legal_documents
      WHERE type = 'sanctions_list' AND last_updated IS NOT NULL
    `).get() as { max_date: string | null } | undefined;
    sanctionsListLastUpdated = listRow?.max_date || null;
  } catch {
    // Ignore errors
  }

  // Check sanctions sync metadata
  let sanctionsLastSync: string | null = null;
  try {
    const syncRow = db.prepare(`
      SELECT last_sync_date
      FROM sanctions_sync_metadata
      WHERE id = 1
    `).get() as { last_sync_date: string } | undefined;
    sanctionsLastSync = syncRow?.last_sync_date || null;
  } catch {
    // Table might not exist yet
  }

  // Calculate staleness warning (7 day threshold — sanctions change frequently)
  const stalenessWarning = calculateStalenessWarning(sanctionsListLastUpdated, sanctionsLastSync);

  return {
    sanctions_list_last_updated: sanctionsListLastUpdated,
    sanctions_last_sync: sanctionsLastSync,
    staleness_warning: stalenessWarning
  };
}

/**
 * Generate staleness warning if data is >7 days old.
 * Sanctions have a shorter threshold than other legal data because lists change frequently.
 */
function calculateStalenessWarning(
  sanctionsListDate: string | null,
  syncDate: string | null
): string | null {
  const now = new Date();
  const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

  const warnings: string[] = [];

  if (sanctionsListDate) {
    const listTimestamp = new Date(sanctionsListDate);
    if (listTimestamp < sevenDaysAgo) {
      const daysOld = Math.floor((now.getTime() - listTimestamp.getTime()) / (24 * 60 * 60 * 1000));
      warnings.push(`WARNING: Sanctions list data is ${daysOld} days old - designations and delistings may have occurred since last update`);
    }
  } else {
    warnings.push('Sanctions list update timestamp unavailable — verify against live OFAC/EU/UN sources');
  }

  if (syncDate) {
    const syncTimestamp = new Date(syncDate);
    if (syncTimestamp < sevenDaysAgo) {
      const daysOld = Math.floor((now.getTime() - syncTimestamp.getTime()) / (24 * 60 * 60 * 1000));
      warnings.push(`Sanctions sync data is ${daysOld} days old - new designations may be missing`);
    }
  }

  return warnings.length > 0 ? warnings.join('. ') : null;
}

/**
 * Get source authority disclosure.
 */
function getSourceAuthority(): SourceAuthority {
  return {
    primary_source: 'OFAC SDN List, EU Consolidated Sanctions List, UN Security Council Sanctions Committees',
    authority_level: 'official',
    verification_required: 'ALWAYS cross-check with official OFAC/EU/UN sanctions lists before relying on output in sanctions screening or compliance work. Sanctions change frequently.'
  };
}

/**
 * Wrapper type for tool responses that includes metadata.
 */
export interface ToolResponse<T> {
  /** Tool-specific results */
  results: T;

  /** Professional-use metadata and warnings */
  _metadata: ResponseMetadata;
}
